### ISSUE TITLE
Explore using Github Packages instead of Docker for container hosting

### ISSUE THREAD

**Issue by schmidtw** [fsfe/reuse-action#30] opened 2024-06-20 22:21 UTC
Since the reuse-action is focused on Github Actions and Github provides free container hosting would the project consider using the Github hosting?

We just ran into cases where docker.io is not allowing authentication & while no hosting service is perfect, Github has a vested interest in keeping Github Actions working and subsequently the Package hosting needed for that infrastructure is critical to Github.

```
0 building with "default" instance using docker driver
  
  #1 [internal] load build definition from Dockerfile
  #1 transferring dockerfile: 359B done
  #1 DONE 0.0s
  
  #2 [auth] fsfe/reuse:pull token for registry-1.docker.io
  #2 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/fsfe/reuse:3
  #3 ERROR: failed to authorize: failed to fetch oauth token: unexpected status from POST request to https://auth.docker.io/token: 503 Service Unavailable
  ------
   > [internal] load metadata for docker.io/fsfe/reuse:3:
  ------
  Dockerfile:5
  --------------------
     3 |     # SPDX-License-Identifier: GPL-3.0-or-later
     4 |     
     5 | >>> FROM fsfe/reuse:3
     6 |     
     7 |     # Copy reuse wrapper used as entrypoint
  --------------------
  ERROR: failed to solve: fsfe/reuse:3: failed to resolve source metadata for docker.io/fsfe/reuse:3: failed to authorize: failed to fetch oauth token: unexpected status from POST request to https://auth.docker.io/token: 503 Service Unavailable
```

**Comment by mxmehl** [comment] 2024-06-21 08:08
That's weird, thanks for the report. So is this a problem between GitHub Actions (Runner) and DockerHub?

Releasing images on an alternative container registry would be a task for the reuse-tool repo. I've left a comment here: https://github.com/fsfe/reuse-tool/issues/865#issuecomment-2182229678

I'd close this issue here as it doesn't seem to be caused by the reuse action per se. If you disagree, please comment.

**Closed by mxmehl** 2024-06-21 08:08 UTC
